### ISSUE TITLE
Grafana Flame Graph for profiling data

### ISSUE THREAD

**Issue by RoySunnySean007** [perfana/jfr-exporter#3]
Hi @PeterPaul-Perfana ,

Thanks for this awesome jfr exporter, do you consider using Grafana Flame Graph for visualization? i.e, https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/flame-graph/

Thanks,
Roy

**Comment by PeterPaul-Perfana** [comment]
Hi Roy, glad you like the jfr-exporter! For cpu flamegraphs you can use Grafana Labs pyroscope. The agent jars can work side by side. 

It is an interesting idea to also get flamegraphs for other types of events, such as monitor lock times, but currently we have no plans to add it to the exporter. 

Our main goal is to get quick insights into the jfr events (of multiple jvms) in a dashboard.
